name: "Timefolders - Principle Centred Productivity "
description: "A place to find and discuss concepts and ideas that can help make life better"
main_keywords: "productivity, Motivation"
author: "Bernard Hamann"
copyright: "2014"

# Pagination

# Dependencies
markdown:        rdiscount
pygments:         true

# Permalinks
permalink:        /:categories/:title/index.html

# Server
base_url: /

# Custom vars
